# Generated by Django 4.1.7 on 2023-03-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Medicine',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='Medicine',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
